#!/bin/bash

logfile=~/FoxServer/server_running.log
MONTH=`date +%m`
YEAR=`date +%Y`
# This is reliable on the first day of a month, but not on the last day or two
PREV_MONTH=`date +%m -d 'last month'`
PREV_YEAR=`date +%Y -d 'last year'`
#PREV_MONTH=10
if [ $PREV_MONTH -eq 12 ]
then
    YEAR=$PREV_YEAR
fi
echo For Year: $YEAR

DIR=/home/tlmmgr/FoxServer/$YEAR
ARCHIVE_FILE=STP.${YEAR}.${PREV_MONTH}.tar
cd $DIR
if [ -d $PREV_MONTH ]
then
    echo "Archiving Prev Month : $PREV_MONTH to $ARCHIVE_FILE"
    tar -cf $ARCHIVE_FILE --remove-files ${PREV_MONTH}

    if [ $? -eq 0 ]
    then
        gzip $ARCHIVE_FILE
        echo "Done .... ${ARCHIVE_FILE}.gz"
    else
        echo "ERROR creating $PREV_MONTH archive file"
        exit 1
    fi

else
    if [ -f ${ARCHIVE_FILE}.gz ]
    then
        echo "Prev Month $PREV_MONTH is already archived"
    else
        echo "Prev Month $PREV_MONTH is MISSING!"
        exit 1
    fi
fi

exit 0
