#!/bin/bash

DATE=`date +%Y-%m-%d-%T`
DIR=~/FoxServer/extract2
password=$(/bin/cat ~/.fox_pw)

function extract {
    ID=$1
    LOGDIR=$2
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e " SELECT * FROM Fox${ID}RTTELEMETRY order by resets, uptime; " | sed 's/\t/,/g' > $DIR/$LOGDIR/Fox${ID}rttelemetry.log
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e " SELECT * FROM Fox${ID}MINTELEMETRY order by resets, uptime; " | sed 's/\t/,/g' > $DIR/$LOGDIR/Fox${ID}mintelemetry.log
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e " SELECT * FROM Fox${ID}MAXTELEMETRY order by resets, uptime; " | sed 's/\t/,/g' > $DIR/$LOGDIR/Fox${ID}maxtelemetry.log
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e " SELECT * FROM Fox${ID}RADTELEMETRY order by resets, uptime, type; " | sed 's/\t/,/g' > $DIR/$LOGDIR/Fox${ID}radtelemetry.log
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e " SELECT * FROM Fox${ID}RAD2TELEMETRY order by resets, uptime, type; " | sed 's/\t/,/g' > $DIR/$LOGDIR/Fox${ID}radtelemetry2.log
}

function extractHerci {
    ID=$1
    LOGDIR=$2
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e " SELECT * FROM Fox${ID}HERCI_HS order by resets, uptime; " | sed 's/\t/,/g' > $DIR/$LOGDIR/Fox${ID}herciHSdata.log
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e " SELECT * FROM Fox${ID}HERCI_HS_HEADER order by resets, uptime; " | sed 's/\t/,/g' > $DIR/$LOGDIR/Fox${ID}herciHSheader.log
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e " SELECT * FROM Fox${ID}HERCI_HS_PACKET order by resets, uptime; " | sed 's/\t/,/g' > $DIR/$LOGDIR/Fox${ID}herciHSpackets.log
}

function packageLogs {
    ID=$1
    LOGDIR=$2
    cd $DIR/$LOGDIR
    rm -rf FOXDB
    tar cf serverlogs.tar *.log
    gzip -f serverlogs.tar
    cp -f serverlogs.tar.gz ~/tlm/$LOGDIR
    ~/cron/convertDB.py .
    tar cf FOXDB.tar FOXDB
    gzip -f FOXDB.tar
    cp -f FOXDB.tar.gz ~/tlm/$LOGDIR
}

extract 1 ao85
packageLogs 1 ao85
extract 2 radfxsat
packageLogs 2 radfxsat

#rm -f *.log
