#!/bin/bash

DATE=`date +%Y-%m-%d-%T`
DIR=~/FoxServer/extract
mysql --user=g0kla --password=amsatfox --database=FOXDB --skip-column-names -e " SELECT * FROM Fox1RTTELEMETRY order by resets, uptime; " | sed 's/\t/,/g' > $DIR/Fox1rttelemetry.log
mysql --user=g0kla --password=amsatfox --database=FOXDB --skip-column-names -e " SELECT * FROM Fox1MINTELEMETRY order by resets, uptime; " | sed 's/\t/,/g' > $DIR/Fox1mintelemetry.log
mysql --user=g0kla --password=amsatfox --database=FOXDB --skip-column-names -e " SELECT * FROM Fox1MAXTELEMETRY order by resets, uptime; " | sed 's/\t/,/g' > $DIR/Fox1maxtelemetry.log
mysql --user=g0kla --password=amsatfox --database=FOXDB --skip-column-names -e " SELECT * FROM Fox1RADTELEMETRY order by resets, uptime, type; " | sed 's/\t/,/g' > $DIR/Fox1radtelemetry.log
mysql --user=g0kla --password=amsatfox --database=FOXDB --skip-column-names -e " SELECT * FROM Fox1RAD2TELEMETRY order by resets, uptime, type; " | sed 's/\t/,/g' > $DIR/Fox1radtelemetry2.log

cd $DIR

# Clean out the old log files
rm -f FOXDB/*.log

# Create the archive for FoxTelem V1.02
tar cf serverlogs.tar *.log
gzip -f serverlogs.tar
cp -f serverlogs.tar.gz ~/tlm/ao85

# Convert the V1.02 logs into V1.03 Segmented DB
~/cron/convertDB.py .
tar cf FOXDB.tar FOXDB
gzip -f FOXDB.tar
cp -f FOXDB.tar.gz ~/tlm/ao85
