#!/bin/bash

# Script to check if FOX has had a new reset

DATE=`date +%Y-%m-%d-%T`
DIR=~/cron
LOG=max_reset.log
OPS_DIR=~/tlm/ops
password=$(/bin/cat ~/.fox_pw)
MAIL_TO="chrisethompson@gmail.com wa4sca@gmail.com marklhammond@gmail.com glasbrenner@mindspring.com"
#MAIL_TO="chrisethompson@gmail.com"

function checkMaxReset {
    ID=$1
    FOX=$2
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e "SELECT max(resets) from STP_HEADER where id=$ID ;" | sed 's/\t/,/g' > $DIR/$ID$LOG

    RESET=`/bin/cat $DIR/$ID$LOG | grep -v NULL`
    if [ ! -z "$RESET" ]
    then
    #echo "Found $(/bin/awk -F',' '{print $1}' $OPS_DIR/${FOX}${ID}T0.txt | grep $RESET  )" 
    case "$(/bin/awk -F',' '{print $1}' $OPS_DIR/${FOX}${ID}T0.txt | grep $RESET | wc -l )" in 

    0) echo "$FOX $ID is missing latest reset $RESET in the T0 File. $(date)" > /tmp/resets.out
    #echo "$FOX $ID is missing latest reset $RESET in the T0 File. $(date)" 
        /usr/bin/mail  -aFrom:tlmmgr@amsat.org -s "Fox $ID missing reset" $MAIL_TO < /tmp/resets.out
#        rm /tmp/resets.out
    ;;

    1) #all seems well
    ;;

    esac
    fi
}

checkMaxReset 1 FOX
checkMaxReset 2 FOX
checkMaxReset 3 FOX
checkMaxReset 4 FOX
checkMaxReset 5 FOX
#checkMaxReset 6 FOX
checkMaxReset 10 LTM
