#!/bin/bash

# Script to check if FOX has had a new reset

DATE=`date +%Y-%m-%d-%T`
DIR=~/cron
LOG=max_reset.log
OPS_DIR=~/tlm/ops
password=$(/bin/cat ~/.fox_pw)
MAIL_TO="g0kla@arrl.net wa4sca@gmail.com marklhammond@gmail.com glasbrenner@mindspring.com"
#MAIL_TO="g0kla@arrl.net"

function checkMaxReset {
    ID=$1
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e "SELECT max(resets) from STP_HEADER where id=$ID ;" | sed 's/\t/,/g' > $DIR/$ID$LOG

    #/bin/grep -Fv  $DIR/max_reset.log  $OPS_DIR/FOX${1}T0.txt > $DIR/missing_resets.log
    #case "$(cat $DIR/missing_resets.log  | wc -l)" in
    RESET=`/bin/cat $DIR/$ID$LOG | grep -v NULL`
    if [ ! -z "$RESET" ]
    then
    case "$(/bin/grep $RESET $OPS_DIR/FOX${ID}T0.txt  | wc -l)" in

    0) echo "Fox $ID is missing latest reset $RESET in the T0 File. $(date)" > /tmp/resets.out
        /usr/bin/mail -s "Fox $ID missing reset" $MAIL_TO < /tmp/resets.out
#        rm /tmp/resets.out
    ;;

    1) #all seems well
    ;;

    esac
    fi
}

checkMaxReset 1
checkMaxReset 2
checkMaxReset 3
checkMaxReset 4
checkMaxReset 5
#checkMaxReset 6
