#!/bin/bash

# Script to check if FOX has had a new reset

DATE=`date +%Y-%m-%d-%T`
DIR=~/cron
OPS_DIR=~/tlm/ops
password=$(/bin/cat ~/.fox_pw)

function checkMaxReset {
    ID=$1
    mysql --user=g0kla --password=$password --database=FOXDB --skip-column-names -e "SELECT max(resets) from STP_HEADER ;" | sed 's/\t/,/g' > $DIR/max_reset.log

    #/bin/grep -Fv  $DIR/max_reset.log  $OPS_DIR/FOX${1}T0.txt > $DIR/missing_resets.log
    #case "$(cat $DIR/missing_resets.log  | wc -l)" in
    RESET=`/bin/cat  $DIR/max_reset.log`
    case "$(/bin/grep $RESET $OPS_DIR/FOX${1}T0.txt  | wc -l)" in

    0) echo "Fox $1 is missing latest reset $RESET in the T0 File. $(date)" > /tmp/resets.out
        /bin/mail -s "Fox $1 missing reset" g0kla@arrl.net < /tmp/resets.out
        rm /tmp/resets.out
    ;;

    1) #all seems well
    ;;

    esac

}

checkMaxReset 1
