#!/bin/bash

DATE=`date +%Y%m%d`
logfile=~/FoxServer/processimage_running${DATE}.log
server=`/bin/hostname`
process=processImages.py

case "$(/bin/ps auxwww | /bin/grep $process | /bin/grep -v grep | wc -l)" in

0) echo "$process  is not running, restarting $(date)" >> $logfile
    cd ~/cron
    /bin/ps auxwww | grep $process > /tmp/ps.out
    ~/cron/$process ~/FoxServer/images & >> $logfile 2>&1 &
    /bin/mail -s "$server was not running $process and it was restarted" g0kla@arrl.net 16465751481@tmomail.net < /tmp/ps.out
    rm /tmp/ps.out
;;

1) #all seems well, so check it is actually responding
;;

*) echo "$process running MULTIPLE times $(date)" >> $logfile
    /bin/mail -s "$server is running multipe copies of $process" g0kla@arrl.net 16465751481@tmomail.net <<EOF
Multiple copies
EOF
;;
esac
