#!/bin/bash

if [ -f ~/cron/PAUSE_SERVER ]; then
    exit 0
fi

logfile=~/FoxServer/service_running.log
server=`/bin/hostname`

case "$(/bin/ps auxwww | /bin/grep FoxService.jar | /bin/grep -v grep | wc -l)" in

0) echo "FoxService is not running on $server, restarting $(date)" >> $logfile
    cd ~/FoxServer
    /bin/ps auxwww | /bin/grep FoxService.jar > /tmp/ps.out
    /bin/cat ~/.foxrpt_pw | /usr/bin/java -Xmx64M -Xms32M -jar ~/FoxServer/FoxService.jar foxrpt FOXDB 8080 & >> $logfile 2>&1 &
    /usr/bin/mail -s "Fox WEB Service was not running on $server and was restarted" g0kla@arrl.net 16465751481@tmomail.net < /tmp/ps.out
    rm /tmp/ps.out
;;

1) #all seems well, so check it is actually responding
;;


esac
