#!/bin/bash
if [ -f ~/cron/PAUSE_SERVER ]; then
    exit 0
fi

logfile=~/FoxServer/server_lsof_check
server=`/bin/hostname`

bigFiles=$(ls -hl ~/FoxServer/*.log | awk '{print $5}' | grep "G" | wc -l)
lsofCheck=$(/usr/bin/lsof | grep tlmmgr | grep java | grep sock | wc -l)

if [ $bigFiles -ne 0 ]
then
echo "SERVER LOGFILE TOO LARGE: Server may be out of control"
    /usr/bin/mail -s "$server LOGFILE too large for FoxServer" g0kla@arrl.net 16465751481@tmomail.net <<EOF
$server Logfile too large for Server
EOF
exit 1
fi

if [ $lsofCheck -gt 10 ]
then
    /usr/bin/mail -s "$server Holding $lsofCheck sockets" g0kla@arrl.net 16465751481@tmomail.net <<EOF
$server TELEM SERVER HOLDING TOO MANY SOCKETS: Server may be out of control
EOF
exit 1
fi

case "$(/bin/ps auxwww | /bin/grep FoxServer.jar | /bin/grep -v grep | wc -l)" in

0) echo "FoxServer is not running, restarting $(date)" >> $logfile
    cd ~/FoxServer
    /bin/ps auxwww | grep FoxServer.jar > /tmp/ps.out
    /bin/cat ~/.fox_pw | /usr/bin/java -Xmx128M -Xms32M -jar ~/FoxServer/FoxServer.jar g0kla FOXDB & >> $logfile 2>&1 &
    /usr/bin/mail -s "$server was not running FoxServer and it was restarted" g0kla@arrl.net 16465751481@tmomail.net < /tmp/ps.out
    rm /tmp/ps.out
;;

1) #all seems well, so check it is actually responding
;;

*) echo "FoxServer running MULTIPLE times $(date)" >> $logfile
    /bin/mail -s "$server is running multipe copies of FoxServer" g0kla@arrl.net 16465751481@tmomail.net <<EOF
Multiple copies
EOF
;;
esac
