#!/bin/bash

logfile=~/FoxServer/service_running.log

case "$(/bin/ps auxwww | /bin/grep FoxService.jar | /bin/grep -v grep | wc -l)" in

0) echo "FoxService is not running, restarting $(date)" >> $logfile
    cd ~/FoxServer
    /bin/ps auxwww | /bin/grep FoxService.jar > /tmp/ps.out
    /bin/cat ~/.fox_pw | /usr/bin/java -jar ~/FoxServer/FoxService.jar foxrpt FOXDB 8080 & >> $logfile 2>&1 &
    /bin/mail -s "TEST Fox WEB Service was not running and was restarted" 16465751481@tmomail.net < /tmp/ps.out
    rm /tmp/ps.out
;;

1) #all seems well, so check it is actually responding
;;


esac
