#!/bin/bash

if [ -f ~/cron/PAUSE_SERVER ]; then
    exit 0
fi

logfile=~/FoxServer/stream_running.log
server=`/bin/hostname`

case "$(/bin/ps auxwww | /bin/grep FoxStream.jar | /bin/grep -v grep | wc -l)" in

0) echo "FoxStream is not running on $server, restarting $(date)" >> $logfile
    cd ~/FoxServer
    /bin/ps auxwww | /bin/grep FoxStream.jar > /tmp/ps.out
    /bin/cat ~/.foxrpt_pw | /usr/bin/java -jar ~/FoxServer/FoxStream.jar foxrpt FOXDB & >> $logfile 2>&1 &
    /bin/mail -s "Fox Stream was not running on $server and was restarted" g0kla@arrl.net 16465751481@tmomail.net < /tmp/ps.out
    rm /tmp/ps.out
;;

1) #all seems well, so check it is actually responding
;;


esac
