#!/bin/bash

logfile=~/FoxServer/service_running.log

case "$(/bin/ps auxwww | /bin/grep FOXDB_COPY | /bin/grep -v grep | wc -l)" in

0) echo "FoxService is not running on FOXDB_COPY, restarting $(date)" >> $logfile
    cd ~/FoxServer
    /bin/ps auxwww | /bin/grep FoxService.jar > /tmp/ps.out
    echo amsatfox | /usr/bin/java -jar ~/FoxServer/FoxService.jar foxrpt FOXDB_COPY 8081 & >> $logfile 2>&1 &
    /bin/mail -s "TEST Fox WEB Service for FOXDB_COPY was not running and was restarted" 16465751481@tmomail.net < /tmp/ps.out
    rm /tmp/ps.out
;;

1) #all seems well, so check it is actually responding
;;


esac
