#!/bin/bash

# Given a month directory, this script then processes each of thedays
echo Processing STP dirs in month $1

for d in $( ls $1 ); do
    echo Processing: $d
     /bin/cat ~/.fox_pw  | java -jar FoxServer.jar g0kla FOXDB_COPY -f $1/$m/$d
done
