#!/bin/bash

# Given a Year directory, this script lists the months and then processes each of thedays
echo Processing STP dirs in year $1

for m in $( ls $1 ); do
    echo Month: $m
    for d in $( ls $1/$m ); do
        echo Processing: $d
	echo amsatfox | java -jar FoxServer.jar g0kla FOXDB_COPY -f $1/$m/$d
    done
done
